### ISSUE TITLE
Adventurer's Pickaxe Dupes Itself

### ISSUE THREAD

**Issue by ghost** [Necr0/ConvenientAdditions#10]
I went to the underground, mined some ores, and came back to my house; what i see! i have 2 times adventurer's pickaxe with same durability! what is this? and it is happening 4. times. and again same durability. 
using minecraft 1.11.2 forge 13.20.0.2206 and latest mod version
edit: omg it is 3 times duped now!!
edit: i saw it when duping. i am using gamerule keepInventory true. **when i die, it dupes itself 1 times.**

**Comment by QbDesu** [comment]
Thanks for reporting. Apparently the Soulbound handler does clash with the gamerule. It shouldn't be hard to fix it though. Thank you for reporting the bug, I will fix it soon. I would have liked to respond sooner but unfortunately I had some internet problems. So, sorry to keep you waiting.

**Comment by QbDesu** [comment]
fixed in the next version
