### ISSUE TITLE
[1.0.16-build26] client crash when using tome of transmutation

### ISSUE THREAD

**Issue by kreezxil** [Necr0/ConvenientAdditions#12]
I have player on my server that has crashed twice while using the Tome of Transmutation.

These two attached reports I think I essentially identically and sadly don't implicate a mod specifically.

http://pastebin.com/pggxVb1B

http://pastebin.com/T74WpTBt

I'm trying to find out what exactly the player is doing to cause the crash and will update accordingly if you have not provided a solution in the mean time. :)

**Comment by QbDesu** [comment]
unfortunately I'm not able to work with just that crash report. Some item's model seems to be broken but I can not say if CA is at fault or another mod or core mod even. But I'll leave the report open for now.

**Comment by kreezxil** [comment]
I"m being told by the players that crash occurs when they open the book.
