### ISSUE TITLE
New Version Crashes on Server

### ISSUE THREAD

**Issue by ghost** [Necr0/ConvenientAdditions#13]
i'm trying to make a dedicated server with my modpack that includes Convenient Additions 1.1. b28 but it crashes. any idea?
[crash-2017-02-27_23.13.17-server.txt](https://github.com/Necr0/ConvenientAdditions/files/804900/crash-2017-02-27_23.13.17-server.txt)

**Comment by QbDesu** [comment]
Thank you for reporting it I'll try to fix it as soon as possible and release a hotfix.

**Comment by QbDesu** [comment]
seems like I fixed it now. strangely enough, it wasn't new code that broke but quite old code that worked before. anyways fix should be released as v.1.1-b29 very soon.

**Comment by QbDesu** [comment]
should be available [here](https://minecraft.curseforge.com/projects/convenient-additions/files/2387117) now.
