### ISSUE TITLE
Little Request

### ISSUE THREAD

**Issue by ghost** [Necr0/ConvenientAdditions#15]
Can you add hexxit flover (Hexbiscus) and hexxit gear armors please? =) i really miss them

**Comment by QbDesu** [comment]
As I already stated in #8:

> Also, no, I will not add Hexical Gear to my mod. The reasons being 1. I don't own the mod and will not just copy/steal other mods, 2. the mod doesn't aim for such things, the mods purpose is to assist vanilla Minecraft and new tiers of tools or armor are not a part of that, hence the titanium ore which was placed in between iron and diamond was removed a while ago.

Sorry but it just wouldn't fit into my mod. Also I'm not really an enthusiast of mods that add a better tier of armor or weapons when there is no real need for them.

However, some of the respective effects are spread along multiple trinkets which were introduced in CA v.1.2:
- Tribal Armor:
  - Jump Boost III: The Jump Trinkets
    - Cloud in a Jar -> Double Jump
    - Slime Balloon -> Higher Jumping
    - Cloud in a Slime Balloon -> Higher Jumping and Double Jump
    - Ender Cloud Balloon -> Even Higher Jumping and Triple Jump
  - Night Vision: Ring of Sunlight (kinda)
- Scale Armor:
  - Fire Resistance: The Fire Protection Trinkets
    - Nether Talisman -> no damage from magma
    - Fireproof Cloak -> prevents burning + lower damage from fire
    - Nether Cloak -> no damage from magma, prevents burning, even lower damage from fire, lower damage from lava
- Thief Armor:
  - Speed: The Mobility Trinkets (Wind Gem and the upgraded version Valkyrie Wings respectively)

Also there will be more trinkets soon:
- band of regeneration (name not final): a regeneration trinket
- ring of gluttony: an improved ring of saturation that eliminates the need for food entirely
- a haste trinket that increases mining speed slightly
- a combined version of the better ring of gluttony and the regeneration trinket
- rocket pack: a trinket that allows accelerating significantly with the elytra by pressing the forward key

But for now I'll focus on getting the guide book done. Best regards,
 	 - Necro

**Comment by ghost** [comment]
hmmmm. okay necro! we are waiting for your good news :) about new version that includes that new things :)) get luck with!

**Comment by QbDesu** [comment]
The version I am talking about(v1.2) was released yesterday https://minecraft.curseforge.com/projects/convenient-additions/files/2394664

**Comment by ghost** [comment]
thanks so much! and i found a bug, it is a compatibility bug. Tough As Nails mod, provides temperature, and if i wear the ring of sunlight, i am getting burning :D can you fix this please? and ah, when i wear the cloaks, they don't shown on me. why didn't you add a looking for this? it would be nice! but you need to know also there are already capes from general minecraft. 
thanks again, get luck with!

**Comment by QbDesu** [comment]
I'll try to add appearance to some of the trinkets (valkyrie wings, cloaks) at some point in time but for now it's no priority. As far as Tough as Nails is concerned, it should be fixed in v.1.2.1 (currently compiling should be out soon)

**Comment by ghost** [comment]
okay, thank you necro!

**Comment by QbDesu** [comment]
It's approved now. https://minecraft.curseforge.com/projects/convenient-additions/files/2394973

**Comment by ghost** [comment]
yes i installed it and going to try it right now

**Comment by ghost** [comment]
okay it doesn't burn me but all my farm destroyed when i go near my crops with the ring of sunlight equipped. What is it working for? Shouldn't it light the area up as me a torch? Am i wrong?

**Comment by ghost** [comment]
and it destroys also the grass path. it is turning them to a dirt block

**Comment by QbDesu** [comment]
Dammit, I'll look into it.

**Comment by QbDesu** [comment]
Okay currently compiling. Changed the block material to "not quite air"(my own block material). I can't just set it to air because air doesn't receive block updates.

**Comment by ghost** [comment]
hmm okay, and it doesn't effect when there are crop on farmland.(like seed) it effects single farmland(hoed) and grass path

**Comment by QbDesu** [comment]
yes because the material i changed it to before(cake) was considered solid.

**Comment by QbDesu** [comment]
Currently, waiting for approval of v.1.2.2

**Comment by ghost** [comment]
okay. waiting.

**Comment by ghost** [comment]
but i still wondering what this ring working for :D should it light up the area? or what does it do

**Comment by QbDesu** [comment]
It creates a lot of small temporary light sources around you.

**Comment by ghost** [comment]
but i used it (equipped) in my dark house which has no any torches or any lighting source in it, it was still dark after equpping. is it normal?

**Comment by QbDesu** [comment]
I'll have a look.

**Comment by QbDesu** [comment]
Might be because of the cake material

**Comment by ghost** [comment]
okay it was a week ago, let's try it with new version

**Comment by QbDesu** [comment]
![](http://puu.sh/uQ9by/e478591e9e.jpg)

Works fine for me.

**Comment by ghost** [comment]
hmmm yes i see thats nice but it wasn't like that on me. hope it fixed on new version. i hope optifine is not effecting this

**Comment by QbDesu** [comment]
It should be available now: https://minecraft.curseforge.com/projects/convenient-additions/files/2394989

**Comment by ghost** [comment]
okay it is working fine! thanks. but i want to ask a question, when i uneqquip it, my ground/floor still has light. when it will be dark? :D

**Comment by ghost** [comment]
oh it got dark right now, such a little bit long time but it is cool :) thank you necro! good work

**Comment by QbDesu** [comment]
to reduce light updates the light sources will only despawn when there is no player in close proximity. This is done to reduce the impact on frame rate.

**Comment by ghost** [comment]
hmm i see. thanks again

**Comment by ghost** [comment]
and ah, before i forget let me ask another question; why all ornaments are wearable on all baubles slots? :D for example i can wear the ring on all slots. and the cloak too. is there a reason? or is it a bug

**Comment by QbDesu** [comment]
This is intended. I didn't want to limit the players ability to wear any combination of baubles(or ornaments) they want and therefore all baubles are wearable in all slots. So you could in theory wear 4 rings of saturation if you really wanted. The ring of saturation is currently the only bauble that benefits from being equipped mutliple times. E.g. equipping multiple clouds in a jar won't give you any extra jumps or increase your jump height over equipping just one.

**Comment by ghost** [comment]
hmmm.. but i can wear 4 cloaks at same time :D 
but whatever, it is still cool because there are other accessory item mods such as Lost Eclipse, i really like the rings and belts and the other accessories of that mod. It is not completely cool since they don't have textures :D but they said it will be added soon. so i can wear 2 rings from convenient additions and 2 rings from lost eclipse. it is sensible and cool.
