### ISSUE TITLE
Double and triple jump not working

### ISSUE THREAD

**Issue by illumincrotty** [Necr0/ConvenientAdditions#17]
Currently the double and triple jump baubles don't grant me double or triple jump. They increase jump height but don't allow extra jumps.

**Comment by QbDesu** [comment]
Probably related to syncing problems. I'll look into it.

**Comment by QbDesu** [comment]
Weird, looks like I'm not able to reproduce it even when running a dedicated server instance. Which is honestly what I expected because the jump is handled on both sides separately.

**Comment by QbDesu** [comment]
Okay it seems to only be working in the debug environment.

**Comment by QbDesu** [comment]
Alright, I figured it out. It should be fixed in v.1.2.3 which is currently waiting for approval.

**Comment by QbDesu** [comment]
Nevermind, it still has some issues.

**Comment by QbDesu** [comment]
Okay, waiting for approval. Should be up soon (for real this time). Worked out all the quirks.

**Comment by QbDesu** [comment]
It's available now: https://minecraft.curseforge.com/projects/convenient-additions/files/2395518
I was able to fix it thanks to the help of SkySom on the #minecraftforge IRC, just to give proper credit.
