### ISSUE TITLE
Inventory proxy not working 

### ISSUE THREAD

**Issue by illumincrotty** [Necr0/ConvenientAdditions#18]
Easier to show than explain [link](http://imgur.com/a/OQPLW)

Unless I'm fundamentally misunderstanding what these do (which I might be, there's no info on the wiki) I think they're broken

**Comment by QbDesu** [comment]
The second setup should work. I'm gonna have a look at it.

**Comment by QbDesu** [comment]
Oh, looks like most if not all tile entities are broken.

**Comment by QbDesu** [comment]
I'm awfully sorry v.1.2.3 broke all the mod's tile entities (and wiped them). Version 1.2.4 fixes that. It's currently waiting for approval.

**Comment by QbDesu** [comment]
It has been approved. Sorry again. https://minecraft.curseforge.com/projects/convenient-additions/files/2395770
