### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by knoxhack** [Necr0/ConvenientAdditions#19]
Forge: forge-1.10.2-12.18.3.2254
Crash Report:
https://gist.github.com/knoxhack/05826b909c8af6c58fdaf1a7a1adc02a

**Comment by QbDesu** [comment]
First of all, why do you assume my mod caused the error? What did you do to crash the server? Secondly, I do not maintain older versions. If the bug does not occur in the latest released version(v.1.2.4 for Minecraft 1.11.2) I won't fix it.
