### ISSUE TITLE
Can Not Repair Adventurer's Pickaxe

### ISSUE THREAD

**Issue by ghost** [Necr0/ConvenientAdditions#20]
can not repair :S no recipe to repair it :S  please help
i put broken adventurer pickaxe (wood) and put wooden planks but no recipe :(((
using game 1.11.2 mod 1.2.4 b39
edit: i deleted all my mods and it is working now. it is a compatibility issue. i will update this issue when i find which mod causes.

**Comment by ghost** [comment]
okay, it is happening when [IGCM](https://minecraft.curseforge.com/projects/ingameconfigmanager) is installed. (it needs creative core but issue not happens with creative core). please help...

**Comment by ghost** [comment]
is it fixed?

**Comment by QbDesu** [comment]
No, it's just not my mod's fault. Fixing it is up to CreativeMD.

**Comment by ghost** [comment]
oh okay. hope they fix it soon..
