### ISSUE TITLE
Tome crashing

### ISSUE THREAD

**Issue by HeroicConcept** [Necr0/ConvenientAdditions#22]
When I use the tome of transmutation my game crashes when the process completes.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.62+beta.84.jar)
  CCLCorePlugin (CodeChickenLib-1.11.2-2.6.0.254-universal.jar)
  RebornCoreASM (RebornCore-1.11.2-2.13.6.52-universal.jar)
  RBLoadingPlugin (RealBench-1.11.2-1.3.2.jar)
  SFRCore (SolarFluxReborn_1.11.2-2.15r.jar)
  NEICorePlugin (NotEnoughItems-1.11.2-2.2.0.216-universal.jar)
  ForgelinPlugin (Forgelin-1.4.1.jar)
  CoreMod (Aroma1997Core-1.11.2-1.2.0.0.b81.jar)
  MalisisCorePlugin (malisiscore-1.11.2-5.1.1.jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 4/14/17 8:17 AM
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at net.minecraft.item.ItemStack.func_77989_b(ItemStack.java:376)
	at net.minecraftforge.items.ItemStackHandler.setStackInSlot(ItemStackHandler.java:59)
	at net.minecraftforge.items.SlotItemHandler.func_75215_d(SlotItemHandler.java:80)
	at convenientadditions.item.relic.transmutationTome.ContainerTransmutationTome.tickContainer(ContainerTransmutationTome.java:151)
	at convenientadditions.handler.ContainerTickHandler.onPlayerTick(ContainerTickHandler.java:13)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_78_ContainerTickHandler_onPlayerTick_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:360)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:188)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:329)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:164)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:215)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.item.ItemStack.func_77989_b(ItemStack.java:376)
	at net.minecraftforge.items.ItemStackHandler.setStackInSlot(ItemStackHandler.java:59)
	at net.minecraftforge.items.SlotItemHandler.func_75215_d(SlotItemHandler.java:80)
	at convenientadditions.item.relic.transmutationTome.ContainerTransmutationTome.tickContainer(ContainerTransmutationTome.java:151)
	at convenientadditions.handler.ContainerTickHandler.onPlayerTick(ContainerTickHandler.java:13)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_78_ContainerTickHandler_onPlayerTick_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:360)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:188)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 895
	Entity Name: HeroicConcept
	Entity's Exact location: -7.88, 64.00, 230.24
	Entity's Block location: World: (-8,64,230), Chunk: (at 8,4,6 in -1,14; contains blocks -16,0,224 to -1,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:329)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:164)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:215)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@190e0ef
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 340727448 bytes (324 MB) / 1037959168 bytes (989 MB) up to 1037959168 bytes (989 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1024m -Xms256m -XX:PermSize=192m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.38 Powered by Forge 13.20.0.2282 82 mods loaded, 82 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2282.jar) 
	UCHIJAAAA	forge{13.20.0.2282} [Minecraft Forge] (forge-1.11.2-13.20.0.2282.jar) 
	UCHIJAAAA	aroma1997core{${version}} [Aroma1997Core] (Aroma1997Core-1.11.2-1.2.0.0.b81.jar) 
	UCHIJAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.11.2-2.6.0.254-universal.jar) 
	UCHIJAAAA	uncraftingtable{1.7.1-pre14} [Uncrafting Table] ([1.11.2]UncraftingTable-1.7.1-pre14.jar) 
	UCHIJAAAA	accesstweaks{2.1-mc1.11.2} [AccessTweaks] (AccessTweaks-2.1-mc1.11.2.jar) 
	UCHIJAAAA	actuallyadditions{1.11.2-r106} [Actually Additions] (ActuallyAdditions-1.11.2-r106.jar) 
	UCHIJAAAA	aroma1997corehelper{1.0} [Aroma1997Core|Helper] (Aroma1997Core-1.11.2-1.2.0.0.b81.jar) 
	UCHIJAAAA	aromabackup{1.0} [AromaBackup] (AromaBackup-1.11-2.1.0.0.b64.jar) 
	UCHIJAAAA	aromabackuprecovery{1.0} [AromaBackupRecovery] (AromaBackup-1.11-2.1.0.0.b64.jar) 
	UCHIJAAAA	baubles{1.4.3} [Baubles] (Baubles-1.11-1.4.3.jar) 
	UCHIJAAAA	betterbedrockgen{6.0.1} [BetterBedrockGen] (BBG-6.0.1.jar) 
	UCHIJAAAA	bedbugs{@VERSION@} [Bed Bugs] (BedBugs-1.11.2-1.1.7.jar) 
	UCHIJAAAA	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.11-0.11.1.239+9162f74.jar) 
	UCHIJAAAA	birdsnests{1.5.1} [Bird's Nests] (BirdsNests1.11.2-1.5.1.jar) 
	UCHIJAAAA	chameleon{1.11-3.0.2} [Chameleon] (Chameleon-1.11-3.0.2.jar) 
	UCHIJAAAA	codechickenlib{2.6.0.254} [CodeChicken Lib] (CodeChickenLib-1.11.2-2.6.0.254-universal.jar) 
	UCHIJAAAA	chickenchunks{2.3.0.63} [ChickenChunks] (ChickenChunks-1.11.2-2.3.0.63-universal.jar) 
	UCHIJAAAA	cyclopscore{0.10.0} [Cyclops Core] (CyclopsCore-1.11.2-0.10.0.jar) 
	UCHIJAAAA	commoncapabilities{1.3.1} [CommonCapabilities] (CommonCapabilities-1.11.2-1.3.1.jar) 
	UCHIJAAAA	jei{4.3.2.264} [Just Enough Items] (jei_1.11.2-4.3.2.264.jar) 
	UCHIJAAAA	convenientadditions{1.2.4-39} [Convenient Additions] (ConvenientAdditions-1.2.4-build39.jar) 
	UCHIJAAAA	cyclicmagic{1.2.8} [Cyclic] (Cyclic-1.11.2-1.2.8.jar) 
	UCHIJAAAA	elevatorid{1.3.0} [Elevator Mod] (ElevatorMod-1.11.2-1.3.0.jar) 
	UCHIJAAAA	enderstorage{1.0} [EnderStorage] (EnderStorage-1.11.2-2.3.0.112-universal.jar) 
	UCHIJAAAA	endores{1.11.2-r1} [End Ores] (EndOres-1.11.2-r1.jar) 
	UCHIJAAAA	environmentalcreepers{1.1.2} [Environmental Creepers] (environmentalcreepers-1.11.2-1.1.2.jar) 
	UCHIJAAAA	excore{2.0.0-beta1-1.11.2} [EXCore] (EXCore-2.0.0-beta1-1.11.2.jar) 
	UCHIJAAAA	extrautils2{1.0} [extrautils2] (extrautils2-1.11.2-1.3.3.jar) 
	UCHIJAAAA	zerocore{1.11.2-0.1.0.5} [Zero CORE] (zerocore-1.11.2-0.1.0.5.jar) 
	UCHIJAAAA	bigreactors{1.11.2-0.4.5.28} [Extreme Reactors] (ExtremeReactors-1.11.2-0.4.5.28.jar) 
	UCHIJAAAA	flowergirls{1.11.2-1.1.0} [Ender Flowergirls] (flowergirls-1.11.2-1.1.0.jar) 
	UCHIJAAAA	foragecraft{1.11} [ForageCraft] (ForageCraft-1.11.jar) 
	UCHIJAAAA	forgelin{1.4.1} [Forgelin] (Forgelin-1.4.1.jar) 
	UCHIJAAAA	exp{1.2} [Exp Seedling Mod] (GiacomosExperienceSeedling-1.11.2-1.2.jar) 
	UCHIJAAAA	gravestone{1.7.2} [Gravestone] (GraveStone Mod 1.7.2.jar) 
	UCHIJAAAA	hammercore{1.5.1} [Hammer Core] (HammerCore_1.11.2-1.5.1.jar) 
	UCHIJAAAA	hardcoreore{0.0.16} [Hardcore ORE] (HardcoreORE-1.11.2-0.0.16.jar) 
	UCHIJAAAA	helpfultweaks{1.6.0} [Helpful Tweaks] (helpfultweaks_1.11.2-1.6.0.jar) 
	UCHIJAAAA	waila{1.8.13} [Waila] (Hwyla-1.8.13-B26_1.11.jar) 
	UCHIJAAAA	shadowmc{3.7.1} [ShadowMC] (ShadowMC-1.11.2-3.7.5.jar) 
	UCHIJAAAA	tesla{1.3.0.51} [TESLA] (Tesla-1.11-1.3.0.51.jar) 
	UCHIJAAAA	inductioncharger{1.3.1} [Induction Charger] (InductionCharger-1.11-1.3.1.jar) 
	UCHIJAAAA	inventorytweaks{1.62+beta.84.b3ecfb1} [Inventory Tweaks] (InventoryTweaks-1.62+beta.84.jar) 
	UCHIJAAAA	itemscroller{0.11.0} [Item Scroller] (itemscroller-1.11.2-0.11.0.jar) 
	UCHIJAAAA	malisiscore{1.11.2-5.1.1} [MalisisCore] (malisiscore-1.11.2-5.1.1.jar) 
	UCHIJAAAA	malisisdoors{1.11.2-6.1.0} [MalisisDoors] (malisisdoors-1.11.2-6.1.0.jar) 
	UCHIJAAAA	mapwriter{2.7.0} [MapWriter] (MapWriter-1.11.2-2.7.0.jar) 
	UCHIJAAAA	teslacorelib{0.5.0} [Tesla Core Lib] (tesla-core-lib-1.11.2-0.5.0.jar) 
	UCHIJAAAA	mekfarm{0.0.1} [MekFarm] (mekfarm-1.11.2-0.5.0.jar) 
	UCHIJAAAA	metamorph{1.1.2} [Metamorph] (metamorph-1.1.2-1.11.2.jar) 
	UCHIJAAAA	mousetweaks{2.8} [Mouse Tweaks] (MouseTweaks-2.8-mc1.11.2.jar) 
	UCHIJAAAA	mysticalagriculture{1.5.0} [Mystical Agriculture] (mysticalagriculture[1.11.2]-1.5.0a.jar) 
	UCHIJAAAA	recipehandler{0.8} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.8(1.11).jar) 
	UCHIJAAAA	nei{${mod_version}} [Not Enough Items] (NotEnoughItems-1.11.2-2.2.0.216-universal.jar) 
	UCHIJAAAA	orecore{0.7.0} [§6Ore Core] (Ore Core 1.11.2 (v.0.7.0).jar) 
	UCHIJAAAA	overworldquartzgen{1.11.2 - 1.0.0} [OverworldQuartzGen] (OverworldQuartzGen-1.0.0.jar) 
	UCHIJAAAA	packingtape{1.11.0-0.6.1} [Packing Tape] (PackingTape-1.11.0-0.6.1.jar) 
	UCHIJAAAA	pattysmorestuff{stable-1.0.4} [Pattys More Stuff] (PattysMoreStuff-stable-1.0.4.jar) 
	UCHIJAAAA	playerstats2{14r} [Player Stats 2] (PlayerStats2_1.11.2-14r.jar) 
	UCHIJAAAA	pulver{@VERSION@} [Pulver] (Pulver-1.11.x-1.0.0.2.jar) 
	UCHIJAAAA	reborncore{2.13.6.52} [RebornCore] (RebornCore-1.11.2-2.13.6.52-universal.jar) 
	UCHIJAAAA	quantumstorage{4.1.2} [QuantumStorage] (QuantumStorage-1.11.2-4.1.2.jar) 
	UCHIJAAAA	quickleafdecay{1.2.3} [Quick Leaf Decay] (QuickLeafDecay-MC1.11.2-1.2.3.jar) 
	UCHIJAAAA	reborncore-mcmultipart{2.13.6.52} [reborncore-MCMultiPart] (RebornCore-1.11.2-2.13.6.52-universal.jar) 
	UCHIJAAAA	xreliquary{1.11.2-1.3.3.653} [Reliquary] (Reliquary-1.11.2-1.3.3.653.jar) 
	UCHIJAAAA	snad{1.11.2-1.7.03.26a} [Snad] (Snad-1.11.2-1.7.03.26a.jar) 
	UCHIJAAAA	solarfluxreborn{2.15r} [Solar Flux Reborn] (SolarFluxReborn_1.11.2-2.15r.jar) 
	UCHIJAAAA	storagedrawers{1.11.2-4.2.2} [Storage Drawers] (StorageDrawers-1.11.2-4.2.2.jar) 
	UCHIJAAAA	teslafied{1.0.0} [Teslafied] (teslafied-1.11-1.1.0.jar) 
	UCHIJAAAA	teslathingies{@@VERSION@@} [Tesla Powered Thingies] (teslathingies-1.11.2-0.0.2.jar) 
	UCHIJAAAA	thedragonlib{1.11.2-3.1.1} [TheDragonLib] (thedragonlib-1.11.2-3.1.1.jar) 
	UCHIJAAAA	tp{2.2.0-Hotfix} [Tiny Progressions] (tinyprogressions-1.11.2-2.2.0-Hotfix.jar) 
	UCHIJAAAA	usefulrecipes{1.11.2-3.2.0} [UsefulRecipes] (usefulrecipes-3.2.0.jar) 
	UCHIJAAAA	veinminer{0.35.3} [Vein Miner] (VeinMiner-1.11-0.35.3.605+dad98e1.jar) 
	UCHIJAAAA	veinminermodsupport{0.35.3} [Mod Support] (VeinMiner-1.11-0.35.3.605+dad98e1.jar) 
	UCHIJAAAA	vtweaks{1.4.10.1} [V-Tweaks] (VTweaks-1.11.x-1.4.10.1.jar) 
	UCHIJAAAA	wailaharvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.11-1.1.9.jar) 
	UCHIJAAAA	wawla{2.4.0.219} [What Are We Looking At] (Wawla-1.11.2-2.4.0.219.jar) 
	UCHIJAAAA	xnet{1.2.0} [XNet] (xnet-1.2.0.jar) 
	Loaded coremods (and transformers): 
FMLPlugin (InventoryTweaks-1.62+beta.84.jar)
  invtweaks.forge.asm.ContainerTransformer
CCLCorePlugin (CodeChickenLib-1.11.2-2.6.0.254-universal.jar)
  codechicken.lib.asm.ClassHierarchyManager
  codechicken.lib.asm.CCL_ASMTransformer
RebornCoreASM (RebornCore-1.11.2-2.13.6.52-universal.jar)
  reborncore.mixin.transformer.MixinTransformer
RBLoadingPlugin (RealBench-1.11.2-1.3.2.jar)
  pw.prok.realbench.asm.RBTransformer
SFRCore (SolarFluxReborn_1.11.2-2.15r.jar)
  com.mrdimka.solarfluxreborn.core.SFRSerializedTransformer
NEICorePlugin (NotEnoughItems-1.11.2-2.2.0.216-universal.jar)
  codechicken.nei.asm.NEITransformer
ForgelinPlugin (Forgelin-1.4.1.jar)
  
CoreMod (Aroma1997Core-1.11.2-1.2.0.0.b81.jar)
  
MalisisCorePlugin (malisiscore-1.11.2-5.1.1.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	chickenchunks Invalid Fingerprint Reports: - No invalid fingerprints.: 
	enderstorage Invalid Fingerprint Reports: - No invalid fingerprints.: 
	nei Invalid Fingerprint Reports: - No invalid fingerprints.: 
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 2.13.6.52
		Mixin Status: 1
		Runtime Debofucsation 1
		RenderEngine: 0
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['HeroicConcept'/895, l='New World', x=-7.88, y=64.00, z=230.24]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by QbDesu** [comment]
I've tracked it down and it shouldn't be happening from the next version (probably 1.2.5) onward.
