### ISSUE TITLE
Crash on Dedicated Server

### ISSUE THREAD

**Issue by ghost** [Necr0/ConvenientAdditions#24]
please help... thanks..
[crash-2017-05-20_15.29.25-server.txt](https://github.com/Necr0/ConvenientAdditions/files/1016156/crash-2017-05-20_15.29.25-server.txt)

**Comment by TheLimePixel** [comment]
Yup, I get the same. Please fix it fast!

**Comment by QbDesu** [comment]
I see, I will fix it right away.

**Comment by ghost** [comment]
thank you necro 😄

**Comment by QbDesu** [comment]
Waiting for the update to be approved. Should be available soon.
Sorry to keep you waiting. I know such bugs are really bad, especially for modpacks.
Should be available here as soon as it is approved:
https://minecraft.curseforge.com/projects/convenient-additions/files/2422689
Thank you for reporting.
Best regards, Necro.

**Comment by QbDesu** [comment]
It has now been approved:
https://minecraft.curseforge.com/projects/convenient-additions/files/2422689

**Comment by ghost** [comment]
no worry, we have time ^^ thanks a lot.

**Comment by ghost** [comment]
hey necro, why don't you combine all configs into a folder? i saw about 11 convenient additions configs :D it would be good.

**Comment by QbDesu** [comment]
It's because of the way the `@Config` annotation, which is what i use to create the config, works. If I were to do it it would kinda break the ingame config menu by having all categories simply named "convenientadditions" instead of the actual category name because it uses the file name to determine the category's display name.

**Comment by ghost** [comment]
hmm... i just thought most of the mods doing this, so it won't be a problem for your mod... ok. thanks for bug fixes

**Comment by QbDesu** [comment]
The mods likely don't use the `@Config` annotation as it is fairly new but doing it the old way makes loading and saving the config a pain in the ass.

**Comment by ghost** [comment]
ah i see.
btw, i just made my first mod, i'm working on forge and mc APIs, trying to understand them :) i only know how to use eclipse and c++ and a little bit java (learned in school) so if i will be good at coding on MC upon forge, i will make pull requests or try to help Convenient Additions :D because i like this mod and want to help development of it

**Comment by QbDesu** [comment]
Great, I'm always open for help and suggestions. The two most important resources you'll probably need are the [offical MinecraftForge Documentation](http://mcforge.readthedocs.io/en/latest/) and the #minecraftforge IRC channel on EsperNet as well as text tutorials, YouTube tutorials and open source mods for reference:
* [Bedrock Miner's Tutorials](https://bedrockminer.jimdo.com/modding-tutorials/) _**OUTDATED: only use in addition to up-to-date Tutorials**_
* [Wuppy29's Tutorials](http://www.wuppy29.com/minecraft/modding-tutorials/forge-modding-1-8/) _**OUTDATED: only use in addition to up-to-date Tutorials**_
* [Way of Time's BloodMagic GitHub Repo](https://github.com/WayofTime/BloodMagic/tree/1.11/)
* [Vazkii's Quark GitHub Repo](https://github.com/Vazkii/Quark/)
* [Vazkii's Botania GitHub Repo](https://github.com/Vazkii/Botania/)
* [asiekierka's Charset GitHub Repo](https://github.com/CharsetMC/Charset/)

Good luck.

**Comment by ghost** [comment]
thank you so much! i will work on them.

**Comment by ghost** [comment]
hey necro ah, must i make only pull requests? or i can help in another way. because making pull requests is a little bit hard for me, can i help about pixel art or any other way? :D

**Comment by QbDesu** [comment]
Sorry to keep you waiting. I wasn't feeling well in the last 2 days.
Of course you can also help in other ways. If you feel like some texture is bad and you want to provide a better version you can also do that. If you want to submit new textures you also better know what the texture is intended for, so maybe an item or block idea. This brings me to my main point. The best way you can probably help out is by providing ideas for improvement or new features(items and blocks). These ideas should be within reason and fit the mod. This means the ideas shouldn't be for something op or things as simple as just a new tier of armor or tools and weapons. Also ideas should keep in mind that this mod aims to improve vanilla, so all features should have a use in a vanilla environment.
One last thing, if you want to go on with this conversation or have any other questions be sure to contact me in other ways. It's just that a closed issue shouldn't be treated like a messaging channel. You can contact me either via PM on CurseForge or on Discord(Necro#5801).
