### ISSUE TITLE
'Crop' spamming message on server console

### ISSUE THREAD

**Issue by Moustik2002** [Necr0/ConvenientAdditions#26]
Each time users or I trying to use tiled compost soil, the server console begins to spam crop message or beach very often which might grow log size, could you please remove this information message spamming'ish ?

**Comment by QbDesu** [comment]
Oh my, sorry about that. It should be fixed in the next version which will probably be released in just a minute (+some approval time). It also improves compost so it can used on the block above the soil to apply it.

**Comment by QbDesu** [comment]
Should now be available [here](https://minecraft.curseforge.com/projects/convenient-additions/files/2423198).
