### ISSUE TITLE
Tome of transmutation Issue 'xpOverride'

### ISSUE THREAD

**Issue by Moustik2002** [Necr0/ConvenientAdditions#27]
Hello when i tried to open the book in server play nothing happens but in server console this message appears :

https://pastebin.com/HA1ZiEzB

i've tested it on single play and it works but not in server play.

version used : build 53

**Comment by QbDesu** [comment]
this is odd... the server shouldn't even care about that field hence it is marked as client-side only. and it used to work. whatever, i'm fixing it and a patch should be up soon.

**Comment by QbDesu** [comment]
Thank you for reporting it. It should be fixed in the next version which will be available [here](https://minecraft.curseforge.com/projects/convenient-additions/files/2426802) as soon as it is approved.
