### ISSUE TITLE
Mismatch recipes using tome of transmutation

### ISSUE THREAD

**Issue by Moustik2002** [Necr0/ConvenientAdditions#28]
Hi, sorry to bother you again but i don't understand someting. 

I try to transmute  ghast tear using 6 nether warts and 1 spider eye.
But each time i do this i get cocoa.
When i check the recipes cocoa is transmuted using 3 netherwart and 1 spider eye. 

And i have almost 10 xp level to get the tear .

**Comment by QbDesu** [comment]
sorry my bad, both recipes use the same ingredients. I think I'll just replace the cocoa beans one to use seeds instead of nether warts.

**Comment by QbDesu** [comment]
Thanks for reporting it (again ^^). The new version(v.1.3.5) should be available [here](https://minecraft.curseforge.com/projects/convenient-additions/files/2426812) as soon as it is approved. Sorry to inconvenience you.
