### ISSUE TITLE
all i did was fire a arrow and game go boom lol 

### ISSUE THREAD

**Issue by 5kedone** [Necr0/ConvenientAdditions#7]
this is on 1.11.2 latest version i made a blast arrow fired it at a cropper and just as it landed the game went bang not the arrow, if this is the point of the said arrow this is a bit of a harsh item lol

http://pastebin.com/Kpv4w1Cu

**Comment by QbDesu** [comment]
Thanks for reporting it. It should be fixed as soon as the next version releases.
