### ISSUE TITLE
Adventurer's Pickaxe Doesn't Effective On Monster Spawners And 2 More Bugs

### ISSUE THREAD

**Issue by ghost** [Necr0/ConvenientAdditions#9]
tried to break monster spawner, it was toooo slow... please fix it. and some other pickaxe-breakable blocks same.
using minecraft 1.11.2 forge 13.20.0.2206 and latest mod version
more blocks i noticed: furnace, bricks, cauldron, anvil, iron bars, stone bricks
**other bug:** adventurer's pickaxe duplicates itself on death (game-rule keepInventory)
**other bug:** vein miner option doesn't give me the correct ore count when mine. for example there are 4 iron ores between each other. you mine them with adventurer's pickaxe (diamond) (level 35) it will mine 4 of them or 2 of them but you will **get only 1 ore**. if you mine with pickaxe and gain level it will get vein miner property automatically. please fix it...

**Comment by QbDesu** [comment]
same bug as #6 is already fixed but not yet released.

**Comment by ghost** [comment]
when will be the new release? we are really waiting for it.

**Comment by QbDesu** [comment]
the next release will probably be tomorrow afternoon. bugs fixed

**Comment by ghost** [comment]
hope you fixed vein ore count bug. hitting 1 iron ore, broken 2 iron ore, got 1 iron ore...
you can directly delete vein mining property from the pickaxe. it is not useful for me..
